"""followers

Revision ID: 094535637bf4
Revises: 216e692a5d76
Create Date: 2018-01-14 12:10:45.016853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094535637bf4'
down_revision = '216e692a5d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
