"""new fields in user model

Revision ID: 216e692a5d76
Revises: 5182595f60ed
Create Date: 2018-01-08 22:33:37.779353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216e692a5d76'
down_revision = '5182595f60ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
